# Generated by Django 4.2.29 on 2026-04-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_alter_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='all.course'),
        ),
    ]
